### ISSUE TITLE
软件包增加请求

### ISSUE THREAD

**Issue by ljcbaby** [yaya131/AX6-AX3600_Almighty-Edition_Config#14]
请求增加 `ppp-mod-pptp` `luci-proto-ppp` 及其依赖

**Comment by ljcbaby** [comment]
目的: PPtP 客户端

参考: <https://www.right.com.cn/forum/thread-144153-1-1.html>

**Comment by jingleijack** [comment]
> 目的: PPtP 客户端
> 
> 参考: https://www.right.com.cn/forum/thread-144153-1-1.html

蓝奏云网盘里有相关依赖包和插件。

**Comment by ljcbaby** [comment]
![image](https://user-images.githubusercontent.com/46277145/157004716-951b6a2f-6edd-4556-a8fd-213762f608ec.png)

好像确实是缺的，`luci-proto-ppp`是有，但`ppp-mod-pptp`没有，另外`ppp-mod-pptp`依赖`kmod-pptp`.

![image](https://user-images.githubusercontent.com/46277145/157005041-e100bc0b-4a67-4652-bad0-ba04c82ed0c2.png)

**Comment by ljcbaby** [comment]
估计是下面这两行
```text
CONFIG_PACKAGE_kmod-pptp=y
CONFIG_PACKAGE_ppp-mod-pptp=y
```

麻烦了
