### ISSUE TITLE
就离谱，刷好，过了一晚上，WiFi连不上，后台也打不开，我真的！

### ISSUE THREAD

**Issue by HumanMusicX** [yaya131/AX6-AX3600_Almighty-Edition_Config#22]
各种后台地址都打不开！烦死了

**Comment by yaya131** [comment]
不会吧，不可能吧。一切正常啊。最新源码编译的？可能是源码的问题。等更新或者刷回之前的版本，或者蓝奏云里的版本

**Comment by HumanMusicX** [comment]
> 不会吧，不可能吧。一切正常啊。最新源码编译的？可能是源码的问题。等更新或者刷回之前的版本，或者蓝奏云里的版本

已经刷了最新版的固件，明天再看吧
