### ISSUE TITLE
AX6 刷入2022.07.22-1353版本UBI，蓝灯长亮，但无法获取网关地址

### ISSUE THREAD

**Issue by hanzch** [yaya131/AX6-AX3600_Almighty-Edition_Config#26]
手持AX6，13分区已扩容系统，没有刷uboot，恩山来的，看到固件很nice想试试，

然后 按照正常流程从12分区，通过ssh刷入2022.07.22-1353版本的ubi文件（openwrt-ipq807x-generic-redmi_ax6-squashfs-nand-factory.ubi ）到13分区，更新启动13分区

重启后  目前蓝灯亮，但是无法获取网关，就是插上网线也没有IP地址，也没有WIFI

请教大佬，怎么破

**Comment by ModChino** [comment]
+1，不过WiFi能用 网口全没反应 系统能进 也是蓝灯

**Comment by hanzch** [comment]
能连上还好，我这直接ttl....  因为扩容了

**Comment by Melencolia11514** [comment]
我也是这个问题目前还没有什么办法

**Comment by ModChino** [comment]
> 能连上还好，我这直接ttl.... 因为扩容了
> 我也是这个问题目前还没有什么办法

我好像OK了，重新编译了 把NSS去掉了就OK了
添加：
# CONFIG_PACKAGE_nss-firmware-ipq8074 is not set

**Comment by ModChino** [comment]
> > 能连上还好，我这直接ttl.... 因为扩容了
> > 我也是这个问题目前还没有什么办法
> 
> 我好像OK了，重新编译了 把NSS去掉了就OK了 添加： `# CONFIG_PACKAGE_nss-firmware-ipq8074 is not set`

完整好像
```
CONFIG_PACKAGE_kmod-qca-nss-dp=y
CONFIG_PACKAGE_kmod-qca-ssdk-nohnat=y
# CONFIG_PACKAGE_nss-firmware-ipq8074 is not set
# CONFIG_PACKAGE_kmod-qca-nss-drv is not set
# CONFIG_PACKAGE_kmod-qca-nss-drv-vlan-mgr is not set
# CONFIG_PACKAGE_kmod-qca-nss-drv-bridge-mgr is not set
# CONFIG_PACKAGE_kmod-qca-nss-drv-pppoe is not set
# CONFIG_PACKAGE_kmod-qca-nss-ecm is not set
```

**Comment by ModChino** [comment]
> 

如果还有问题，自己fork boos源 回滚到
`d1728c7589ac31d440ae9295c17a4388e8ea1c0e`
然后按照上面添加配置重新编译

别忘了修改Action配置文件里面的openwrt地址

**Comment by hiboy1209** [comment]
大神，我不需要无线，哪里设置改下？

**Comment by ModChino** [comment]
> 能连上还好，我这直接ttl.... 因为扩容了

我之前也ttl了，自己救回来就刷了不死uboot+QSDK养老了，懒得折腾.OP还是推荐X86(软路由)的折腾

**Comment by ModChino** [comment]
> 大神，我不需要无线，哪里设置改下？

上面配置都不关无线的事，全是高通NSS加速的。

**Comment by hiboy1209** [comment]
> > 大神，我不需要无线，哪里设置改下？
> 
> 上面配置都不关无线的事，全是高通NSS加速的。

要是我不要无线，在哪里弄？

**Comment by zisain** [comment]
只能TTL.

**Comment by houuu23** [comment]
我用360网络修复弄好了，可以试试，还是IP地址原因，没网络，网关也进不了

**Comment by hanzch** [comment]
> 

感谢，已经ttl了，关帖
